#+title: R review: explore data structures
#+author: [yourname]
#+startup: overview hideblocks indent
#+property: header-args:R :session *R* :exports both :results output
* README

This file covers main data structures in R:
- Vectors, or ordered n-tuples
- Factor vectors, or vectors for ordered or nominal categories
- Lists, or collections of any other R data structure
- Data frames, or a table of features (cols) and observations (rows)

Most of this material can be found in Lantz, Machine Learning with R
(3e, 2019), Packt. Solutions can be found in GitHub as PDF files.

* TODO Identify and pledge yourself

1) In Emacs, replace the placeholder ~[yourname]~ at the top of this
   file by your own name and write ~(pledged)~ next to it
2) Go with the cursor on the headline and hange the ~TODO~ label to ~DONE~
   by entering ~S-<right>~ ("Shift + right-arrow").

* TODO 

* TODO Wow! Congratulations!

Well done! You've reached the end of this in-class practice file.

If you've completed all steps, you can now upload the Org-mode file to
Canvas (see ~Assignments > In-class practice~.

